---
title: "Read the first INvenTree paper and explore its data!" 
categories: 
 - general
date: 2026-09-04
---

We are excited to announce two major milestones for the India Tree Inventory Network -- **our first publication and its companion metadata explorer dashboard**! 

The first paper from INvenTree has been published in *Biotropica*! The paper, titled *"Harmonizing Distributed Tree Inventory Datasets Across India Can Fill Critical Gaps in Tropical Ecology"*, has been a collaborative effort in the making for a few years now. This paper catalogues a metadatabase of published tree inventory studies across India and associated metadata.   

:::{.callout-note}
Key takeaways:  
- Published tree inventories from India span over 465 km^2 and all of India's tree-d biomes.  
- Only a very small proportion of these datasets are openy available in some form, and a much smaller fraction meets reproducibility standards.  
- However, the majority of authors and potential data owners are based in India, motivating the need for a network that can facilitate data sharing and synthesis in India.  

:::


:::{.center-text}
[Read the paper](https://doi.org/10.1111/btp.70236){.btn .btn-primary target="_blank"}
[Download pdf](../resources/pubs/pdfs/Anujan_et_al_2026_Biotropica.pdf){.btn .btn-primary target="_blank"}
:::

The INvenTree Data Visibility Team has also developed a metadata explorer dashboard from the assembled metadatabase. 
With this database you can find studies of interest by filtering regions, biomes and more!

:::{.center-text}
[Launch the dashboard](https://inventree-paper-explorer.shinyapps.io/inventree_explore_papers_app/){ .btn .btn-primary target="_blank"}
:::

Please help spread the word among your networks.

We would love to hear your feedback on the dashboard and the paper. Please reach out to us at [india-inventree@gmail.com](mailto:india-inventree@gmail.com).