---
# title: "India Tree Inventory Network (INvenTree)"
title: "Newsletter Issue 3 - June 2026"
format: html
embed-resources: true
categories:
 - newsletter
citeproc: true
bibliography: member-pubs.bib
csl: apa-cv.csl
suppress-bibliography: true
# urlcolor: "#08392b"
# fontsize: 11pt
margin-left: 0.5cm
margin-right: 0.5cm
# margin-top: 1.5cm
title-block-banner: assets/tree_zoom.jpg
title-block-banner-color: "#080000"
---

<!-- :::{.block fill=rgb("#08392b") inset="8pt" radius="4pt" width="100%"}
::: -->

:::{.block fill=rgb("#7d6a2a") inset="8pt" radius="4pt" width="100%"}
:::

# Greetings from the India Tree Inventory Network! 
With this periodical, we hope to keep the community updated on working group activities, new members and new and relevant publications by researchers in the network. 

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

**Welcome to new members!**   
Please join us in welcoming new members to the group! Dr. Anzar Khuroo, University of Kashmir, A P Madhavan, Nature Conservation Foundation, Dr. Sudhakar Reddy, National Remote Sensing Centre, Hyderabad, Dr. Sandeep Pulla, National Centre for Biological Sciences and Dr. Jayashree Ratnam, National Centre for Biological Sciences have joined us. 

Do check out our [member directory](https://india-inventree.github.io/members/) to see the full list of members and their affiliations.

:::

<!-- :::{.block fill=rgb("#7d6a2a") inset="8pt" radius="4pt" width="100%"}
::: -->

:::{.square fill=rgb("#08392b")}
:::

# Team Updates

## Network Building
Members: Krishna Anujan (lead), Neha Mohanbabu, Tanaya Nair, Nasla Najeeb, Karun Jose, Mahesh Sankaran  

This working group is focussed on building the network and engaging with members. Updates include:  
1. **In-person meeting**: The first in-person meeting of the India Tree Inventory Network was organised at the National Centre for Biological Sciences, Bengaluru from 16-17 January 2026. Read the full report [here](https://india-inventree.github.io/posts/meeting2026.html).  
2. **Seeking early career members**: We are actively reaching out to new student and early career members to join the network. If you mentor or collaborate with students or postdocs who might benefit from this community, please put them in touch with us at [indiainventree@gmail.com](mailto:indiainventree@gmail.com)  
3. **Group policies**: Following the meeting, we have drafted a collaboration policy for participating in network projects. Please review the document here: [Collaboration Policy](https://india-inventree.github.io/resources/policies/collab.html).   
 


::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

Planned activities:  
**Research papers**: We plan to further the research themes identified at the in-person meeting. Many groups have conducted one or two meetings. The network building team will support the collaborative activities of these groups along with the Data Visibility Team.  


:::

## Data Visibility
Members: Neha Mohanbabu (lead), Krishna Anujan, Nasla Najeeb, Karun Jose  

This working group is focused on making collated datasets accessible and reusable. Current and planned projects:  
1. **Shiny app**: The first Shiny app to visualise INvenTree metadata was launched at the INvenTree in-person meeting! Explore and download the data [here](https://inventree-paper-explorer.shinyapps.io/inventree_explore_papers_app/).  
2. **Collating plot metadata:** This group is currently collating metadata on one-time and repeat census tree inventory plots in India. This will contribute to discussions on collaborative research. If you are a data owner or plot data manager with plot metadata that you would like to contribute, please reach out to [indiainventree@gmail.com](mailto:indiainventree@gmail.com) for details. 

------------------

# Recent Publications from members 
1. @mugal_endemic_2026
2. @wani_climate_2026
3. @joshi_linking_2025

:::{.block fill="luma(230)" inset="8pt" radius="4pt"}

## Have you published a paper with tree inventories recently? Write to us at indiainventree@gmail.com and we'll send it around!

:::

